
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module COUNTING_BUTTON_PRESSES(

	//////////// CLOCK //////////
	input 		          		MAX10_CLK1_50,

	//////////// LED //////////
	output reg		     [3:0]		LEDR,

	//////////// KEY //////////
	input 		     [1:0]		KEY

);


    // Internal registers
    reg [21:0] debounce_counter = 0;  // For debouncing
    reg button_prev = 1;              // Previous button state
    reg [3:0] count = 0;              // 4-bit counter

    // Button is active LOW, so we look for falling edge
    wire button = ~KEY[0];             // Using KEY[0]

    always @(posedge MAX10_CLK1_50) begin
        // Debouncing counter
        debounce_counter <= debounce_counter + 1;
        
        // Check button state every ~10ms
        if (debounce_counter == 0) begin
            // If button was high and is now low (pressed)
            if (button_prev == 1 && button == 0) begin
                // Increment counter
                count <= count + 1;
					 assign LEDR[0] = ~KEY[0];
            end
            button_prev <= button;
        end
        
        // Display count on LEDs
        
    end

endmodule